import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./(user)/_HomeComponents/Header";
import OneCategoryFoods from "./(admin)/admin/foodmenu/OneCategoryFoods";
import { CategoriesProvider } from "./_context/CategoriesContext";
import { FoodsProvider } from "./_context/FoodContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CategoriesProvider>
          <FoodsProvider>{children}</FoodsProvider>
        </CategoriesProvider>
      </body>
    </html>
  );
}